### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by bangonkali** [marykdb/rocksdb-multiplatform#1]
Hi! This is an awesome project. I've been looking for a database implementation I can share with Desktop/Server and Android. Will this work with Android?

**Comment by bangonkali** [comment]
Maybe a guide on how to get started with Android?

**Comment by jurmous** [comment]
Hello @bangonkali! 
Thanks for checking the project out! I made the README more clear on Android support. 
I have build a specific Android version of RocksDB using the setup at: https://github.com/marykdb/rocksdb-android and use that in this Kotlin Multiplatform project.

I also added a quick usage example to the README. The API is the same as the JVM RocksDB version. So you can just add the dependency to a Kotlin enabled Android project and then you can start using this project as in the example.

RocksDB is a lower level key value database which is used as the foundation of multiple databases. You work more with the raw byte arrays. I myself try to implement a higher level database on top of this which works across platforms, but this is not published yet.  

If you have any questions please ask. 😄
